tmp
andreasKroepelin/typst-slides pull request #9
Opened 2023-03-30 10:47 UTC by astrale-sharp

2023-03-30 15:30 UTC, PgBiel requested changes
Hey, thanks for the contribution! I've pointed out several formatting nitpicks - there are probably more instances of them, so make sure to fix those too (but please note that this isn't in any way about the quality of the code, just what I think would be better formatting):

2023-03-30 15:30 UTC, PgBiel commented on slides.typ
> +        subslide : subslide,
Nitpick
```suggestion
        logical-slide: logical-slide,
        subslide: subslide,
```

2023-03-30 15:30 UTC, PgBiel commented on slides.typ
> +    theme : base_theme(),
Nitpick
```suggestion
    data: none,
    theme: base_theme(),
```

2023-03-30 15:30 UTC, PgBiel commented on slides.typ
> +#let slide(theme: base_theme(),max-repetitions : 10, body) = {
Nitpick
```suggestion
#let slide(theme: base_theme(), max-repetitions: 10, body) = {
```

2023-03-30 15:30 UTC, PgBiel commented on examples/simple.typ
> +  data : data(
Nitpick
```suggestion
  data: data(
```

2023-03-30 15:30 UTC, PgBiel commented on theme.typ
> +)= {
Nitpick
```suggestion
) = {
```

2023-03-30 15:31 UTC, PgBiel commented on slides.typ
>          )
Worth discussing this further, but I just wanted to comment that we should probably let themes entirely customize the title slide as well (return a content or similar)

Should also be able to use lambdas for this (with the "big state dict" we discussed previously)

2023-03-31 12:50 UTC, astrale-sharp commented
Hope I havent forgotten any fmt nitpicks, i went a bit fast !

2023-03-31 12:58 UTC, andreasKroepelin commented
Hey, thanks a lot for your contribution! I'm a bit sick at the moment so it will take me a few days until I can properly review this PR. Just as a quick question from scrolling through the code: Is my impression right that you intend to set the theme for every individual slide? That would seem like an rather unfortunate API to me (you also don't do that in LaTeX beamer). I think specifying the theme should happen as an argument to the `#slides`-template function, that initiates the document. Sorry if I just got it wrong, though.

2023-03-31 14:45 UTC, astrale-sharp commented
Take care and rest well!! :heart: 
Indeed I'm not happy about specifying the theme each time..
I will add a state for theme !

2023-03-31 16:33 UTC, astrale-sharp commented
The new commit introduces a state for theme but introduces a bug (why? :() where first page is blank

2023-04-03 09:48 UTC, enseignantePC commented
The bug was due to a locate call
`#let _ = locate(....)` fixed it

2023-04-05 15:09 UTC, closed without merging